version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_HOST}
    depends_on:
      - zookeeper

  # schemareg:
  #   image: docker.io/bitnami/schema-registry:7.2.3
  #   ports:
  #     - "9092:9092"
  #   volumes:
  #     - "kafka_data:/bitnami"
  #   environment:
  #     - SCHEMA_REGISTRY_DEBUG=true
  #     - SCHEMA_REGISTRY_KAFKA_BROKERS=${KAFKA_HOST}

  # go:
  #   image: golang:alpine
  #   tty: true
  #   volumes:
  #     - "./:/golang"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local